behaviors:
  SoccerTwos:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048 # Keep same
      buffer_size: 20480
      learning_rate: 0.0003 # Same as POCA; tweak if needed.
      beta: 0.005 # Regularization parameter for PPO.
      epsilon: 0.2
      lambd: 0.95 # same as POCA.
      num_epoch: 3 # Number of training passes; typically 3-5 for PPO.
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
