behaviors:
  SoccerTwos:
    trainer_type: a2c
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 0.0003
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 12000
